### ISSUE TITLE
Duplicating name issue

### ISSUE THREAD

**Issue by ahmed-hazem-1** [ahmed-hazem-1/Simple-Address-Book-Application#1]
the simple program I made has an issue when adding new contact with same name, the older removed.

**Comment by BasemAkram** [comment]
Show what I had sent for you in watsapp bro

**Comment by BasemAkram** [comment]
👽👽💫

**Comment by BasemAkram** [comment]
Oh

**Comment by BasemAkram** [comment]
My

**Comment by BasemAkram** [comment]
God

**Comment by FurqanHun** [comment]
Hi Ahmed the problem relies in how you're handling the data storage. A dictionary key must be unique, and this line `book[name] = {"Phone": phone, "Email": email}` in your code adds a contact with the given name as the key. If a contact with that name already exists, it overwrites the existing entry.

There are two possible approaches to fix this behavior,
1. Give each contact a unique identifier (UUID) or use incrementing IDs (e.g., `uid = 0`, `uid += 1`) and use that as the key.
2. Use a List instead of dictionary.

Personally, I recommend using uuids (you can use the `uuid` library in python for this) as it simplifies data management and ensures each contact has a unique identifier.

**Comment by ahmed-hazem-1** [comment]
Thank you for your suggestion!

I agree that using UUIDs for each contact is a great idea to avoid conflicts with duplicate names.
I'll update the code to implement this.

Thanks again for your help! @FurqanHun

**Comment by FurqanHun** [comment]
No worries! Happy to help!
